#------------------------------------------------------------------------------------------------------------------------#
# ███████╗███╗   ██╗██████╗ ███████╗██████╗ ████████╗██████╗  █████╗ ███╗   ██╗███████╗██╗      █████╗ ████████╗███████╗ #
# ██╔════╝████╗  ██║██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗████╗  ██║██╔════╝██║     ██╔══██╗╚══██╔══╝██╔════╝ #
# █████╗  ██╔██╗ ██║██║  ██║█████╗  ██████╔╝   ██║   ██████╔╝███████║██╔██╗ ██║███████╗██║     ███████║   ██║   █████╗   #
# ██╔══╝  ██║╚██╗██║██║  ██║██╔══╝  ██╔══██╗   ██║   ██╔══██╗██╔══██║██║╚██╗██║╚════██║██║     ██╔══██║   ██║   ██╔══╝   #
# ███████╗██║ ╚████║██████╔╝███████╗██║  ██║   ██║   ██║  ██║██║  ██║██║ ╚████║███████║███████╗██║  ██║   ██║   ███████╗ #
# ╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ #
#------------------------------------------------------------------------------------------------------------------------#
# Made by SuperMax_8
# https://github.com/SuperMax8/EnderTranslate


mainServer: true
# Connection secret, generated by the plugin, copy paste the same secret in every server using the plugin
secret: ""

# If mainServer is true, port of the websocket
wsPort: 8080
wsUrl: "ws://localhost:8080"

# Tags used for translation placeholders, e.g. [lang]testtest[/lang]
startTag: "[lang]"
endTag: "[/lang]"

# Default language when a player connect
defaultLanguage: english

languages:
  english:
    title: "§7English"


# NEVER CHANGE THIS VALUE
config-version: 1