#------------------------------------------------------------------------------------------------------------------------#
# ███████╗███╗   ██╗██████╗ ███████╗██████╗ ████████╗██████╗  █████╗ ███╗   ██╗███████╗██╗      █████╗ ████████╗███████╗ #
# ██╔════╝████╗  ██║██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗████╗  ██║██╔════╝██║     ██╔══██╗╚══██╔══╝██╔════╝ #
# █████╗  ██╔██╗ ██║██║  ██║█████╗  ██████╔╝   ██║   ██████╔╝███████║██╔██╗ ██║███████╗██║     ███████║   ██║   █████╗   #
# ██╔══╝  ██║╚██╗██║██║  ██║██╔══╝  ██╔══██╗   ██║   ██╔══██╗██╔══██║██║╚██╗██║╚════██║██║     ██╔══██║   ██║   ██╔══╝   #
# ███████╗██║ ╚████║██████╔╝███████╗██║  ██║   ██║   ██║  ██║██║  ██║██║ ╚████║███████║███████╗██║  ██║   ██║   ███████╗ #
# ╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝ #
#------------------------------------------------------------------------------------------------------------------------#
# Made by SuperMax_8
# https://github.com/SuperMax8/EnderTranslate
#
# Wiki: https://supermax-8.gitbook.io/endertranslate/

mainServer: true
# Connection secret, generated by the plugin, copy paste the same secret in every server using the plugin
secret: ""

# If mainServer is true, port of the websocket, change localhost by the ip of this server
wsPort: 8080
wsUrl: "ws://localhost:8080"

# Tags used for translation placeholders, e.g. [lang]testtest[/lang]
startTag: "[lang]"
endTag: "[/lang]"

# Default language when a player connect
defaultLanguage: english

# Editor url (DON'T EDIT IF YOU'RE NOT SURE)
editorURL: http://endertranslate.superlion.fr/

# Languages
# Patterns are the banner patterns for the banner item in the lang gui, each pattern should be identifer;color e.g "dls;0"
# Banners: https://www.gamergeeks.net/apps/minecraft/banners/country-flags
# Banner name to key to enter: https://pastebin.com/EC6pvaV6
# On this site you have a lot of country banners, when you see in the give command for example {Pattern:ls,Color:14}, add a line with "ls;14"
languages:
  english:
    title: §7English
    material: BLUE_BANNER
    patterns:
      - dls;0
      - drs;0
      - cr;14
      - cs;0
      - ms;0
      - sc;14
  french:
    title: §7French
    material: WHITE_BANNER
    patterns:
      - rs;14
      - rs;14
      - ls;11
      - ls;11

# NEVER CHANGE THIS VALUE
config-version: 1